<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net48'">
    <Reference Include="System.ServiceModel" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.1.2" />
  </ItemGroup>

</Project>
